In [5]:
"2020\3\17今天开始学习numpy基础篇"
'''1 基础知识'''
import numpy as np
a = np.arange(15).reshape(3,5)#arange 返回的是数组，而不是列表
print(a)
print(a.ndim,a.shape,a.size,a.dtype.name,a.itemsize)
#     维度   形状   大小   类型  每个元素的字节大小


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2 (3, 5) 15 int32 4
2****************


In [6]:
'''2 创建数组'''
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(b)

print("*****************************")
a = np.zeros((3,4))
print(a)
b = np.ones((2,3),dtype=int)
print(b)
print("**********************************")

#arange 函数返回数组
a = np.arange(1,10,2) #(start,end,step)   必须在numpy里边才可以用
print(a)#[1 3 5 7 9]
b = np.arange(1,3,0.5)#支持小数  range()不支持
a = np.random.random((2,3))
print(a)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
*****************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
**********************************
[1 3 5 7 9]
[[0.33524999 0.72014012 0.43029255]
 [0.25837085 0.20347717 0.39560847]]


In [10]:
print(np.arange(4).reshape(2,2))
print(np.arange(1,5).reshape(2,2))

[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [17]:
'''3 打印数组'''
'''当你打印一个数组，numpy会类似于嵌套列表的方法显示
    0  最后的轴从左往右打印
    0  次后的轴从上到下打印
    0  剩下的轴从上到下打印，每个切片通过一个空行与下一个隔开'''
a = np.arange(6)#1d
b = np.arange(6).reshape(2,3)#2d
c = np.arange(24).reshape(2,3,4)#3d
print(a,\n"*"*10)
print(b,"\n*******")
print(c)
print("***********")
print(np.arange(10000).reshape(100,100))

SyntaxError: unexpected character after line continuation character (<ipython-input-17-9a490fd8d8df>, line 9)

In [20]:
print("*"*10)

**********


In [28]:
"""4基本运算"""
a = np.array([1,2,3,4])
b = np.arange(4)
c = a - b
print(c)#[1 1 1 1]
#sin(c)  #numpy 中的乘法运算符*按元素计算 ，矩阵乘法可以使用dot函数
a = np.array([[1,2],
             [3,4]])
b = np.array([[1,2],
             [3,4]])
print(a*b) #对应位置相乘
print(b.dot(a))#矩阵相乘

a = np.ones((2,3))
a *= 3
print("a 每个位置元素乘以3:\n",a) #每个位置乘以3

a = np.linspace(1,10,3)#(start,end,num)
print(a)

"""sum,min,max  涉及到轴方向运算
axis = 0  #列相加
axis = 1  #行相加"""
a = np.arange(12).reshape(3,4)
print("a:\n", a)
print(a.sum(axis = 0))
print(a.sum(axis = 1))

[1 1 1 1]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
a 每个位置元素乘以3:
 [[3. 3. 3.]
 [3. 3. 3.]]
[ 1.   5.5 10. ]
a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [1]:
"""5 通用函数ufunc
numpy 提供的常见数学函数如 sin  cos exp  ,这些叫做通用函数ufunc   numpy 里边，函数作用是按照数组的元素运算，产生一个数组作为输出"""
import numpy as np
a = np.arange(5)
b = np.exp(a)
c = np.sqrt(a)
d = np.add(b,c)
print(a,b,c,d,)
print("*"*30)
"""索引，切片和迭代
一维数组可以被索引，切片和迭代，就像列表和其他Python序列"""
a = np.arange(10)
print(a)
a[2]




[0 1 2 3 4] [ 1.          2.71828183  7.3890561  20.08553692 54.59815003] [0.         1.         1.41421356 1.73205081 2.        ] [ 1.          3.71828183  8.80326966 21.81758773 56.59815003]
******************************
[0 1 2 3 4 5 6 7 8 9]


2

In [17]:
a[0:2]

array([0, 1])

In [23]:
a[::-1]#翻转


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
for i in a :
    print(i**(1/2),end=",")

0.0,1.0,1.4142135623730951,1.7320508075688772,2.0,2.23606797749979,2.449489742783178,2.6457513110645907,2.8284271247461903,3.0,

In [29]:
"""多维数组可以每个轴有一个索引，这些索引由一个逗号分割的元祖给出"""
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(3,4),dtype=int)#https://www.cnblogs.com/pingwen/p/4803501.html
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [36]:
b[2],b[2,3],b[0:2,2],b[:,2],b[0:2,:]

(array([20, 21, 22, 23]),
 23,
 array([ 2, 12]),
 array([ 2, 12, 22]),
 array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]))

In [37]:
b[-1]#少于轴数的索引被提供，确定的索引被认为是整个切片。

array([20, 21, 22, 23])

In [38]:
"""6、形状操作"""

'6、形状操作'

In [40]:
"""一个数组的形状由每个轴上的元素个数给出"""
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.shape,a.ravel()#flatten the array,

((3, 4), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [52]:
a.reshape(2,6), a.transpose(),a.transpose().shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]]), (6, 2))

In [49]:
a.resize(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [55]:
a = np.floor(10*np.random.random((2,12)))
a

array([[3., 8., 3., 0., 3., 1., 4., 3., 3., 8., 6., 5.],
       [5., 9., 2., 6., 2., 4., 5., 6., 1., 8., 0., 7.]])

In [59]:
b = np.hsplit(a,3)# 分成三个  每个八个元素  还是两行
b

[array([[3., 8., 3., 0.],
        [5., 9., 2., 6.]]), array([[3., 1., 4., 3.],
        [2., 4., 5., 6.]]), array([[3., 8., 6., 5.],
        [1., 8., 0., 7.]])]

In [60]:
c = np.hsplit(a,(3,4))#Split a after the third and the fourth column
c# 在第三第四列后边分割a

[array([[3., 8., 3.],
        [5., 9., 2.]]), array([[0.],
        [6.]]), array([[3., 1., 4., 3., 3., 8., 6., 5.],
        [2., 4., 5., 6., 1., 8., 0., 7.]])]

In [61]:
"""复制和视图
当运算和处理数组是，他们的数据有时被拷贝到新的数组有时不是"""
"""完全不拷贝，简单的赋值不拷贝数组对象或他们的数据"""

'完全不拷贝，简单的赋值不拷贝数组对象或他们的数据'

In [62]:
a = np.arange(12)
b= a 
b is a 
b.shape = (3,4)

True

In [67]:
a.shape

(3, 4)