In [6]:
import numpy as  np
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
len(a)#永远是最外边那维度的个数

2

# numpy  进阶篇  2020\3\19

In [1]:
'''广播原则
不同维度可以相加  ，自动补齐'''

'广播原则'

2 花哨的索引和索引技巧
numpy比普通的Python序列提供更多的索引功能，除了索引整数和切片，   数组可以被整数数组和布尔数组索引

In [2]:
from numpy import *
a= arange(12)**2
i = array([1,2,3,4,5,6])
print(a)
print(a[i])#按照位置索引对应的值

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  4  9 16 25 36]


In [3]:
b = array([[3,4],[7,8]])#二维数组形式位置索引
a[b]#输出形状同b

array([[ 9, 16],
       [49, 64]], dtype=int32)

In [4]:
palette = array( [ [0,0,0],                # 黑色
                   [255,0,0],              # 红色
                   [0,255,0],              # 绿色
                   [0,0,255],              # 蓝色
                   [255,255,255] ] )       # 白色
image = array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                 [ 0, 3, 4, 0 ]  ] )#还是相当于把每一个行向量看成一个单独的数字
palette[image]                            # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [5]:
a = arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
i = array([[0,1],
          [1,2]])
i.shape
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [14]:
j = array( [ [2,1],                        # indices for the second dim
             [3,3] ] )
j.shape

(2, 2)

In [11]:
a[i,j]# i作为横轴   j作为纵轴

array([[ 2,  5],
       [ 7, 11]])

In [15]:
a[:,j]


array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [16]:
a[:,j].shape

(3, 2, 2)

In [ ]:
'''argmax(axis=0\1) 0  对列操作      1  对行操作  同sum'''

In [23]:
a = arange(12).reshape(3,4)
print(a)
print("*"*10)
b= a.sum(axis=0)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**********
[12 15 18 21]


In [20]:
c = a.argmax(axis=0)#每一列的最大值所对应的的索引
c

array([2, 2, 2, 2], dtype=int64)

In [24]:
a.argmax(axis=1)

array([3, 3, 3], dtype=int64)

In [27]:
a.max(axis=0)

array([ 8,  9, 10, 11])

"""赋值"""

In [28]:
a = array([1,2,3,4,5])

In [32]:
a[[0,1]] = 8
a

array([8, 8, 3, 4, 5])

In [37]:
a[[1,2,3]]# 数组形式表示索引位置，才可以导出来多个位置的值  

array([8, 3, 4])

In [38]:
a[2]# 单个索引对应的值基础篇讲过，只需要一个中括号就可以了

3

In [47]:
a = arange(5)
print(a)
a[[0,0,2]]+=1#即便0位置索引出现两次，还是只加一次，  
              #因为Python要求a+=1和a=a+1 等同

a

[0 1 2 3 4]


array([1, 1, 3, 3, 4])

# 通过布尔值来索引值

In [51]:
a = arange(12).reshape(3,4)
print(a)
b = a>4
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [54]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
a = arange(12).reshape(3,4)
print(a)
b1 = array([False,True,True])             # first dim selection
b2 = array([True,False,True,False])       # second dim selection
a[b1,:] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a[:,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [60]:
a[b1,b2]# 第二行的第一个   第三行的第三个

array([ 4, 10])

# ix_函数

In [2]:
from numpy import *
a = array([2,3,4,5])
b = array([6,7,8])
c = array([9,8,7])
ax,bx,cx = ix_(a,b,c)

In [3]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [4]:
bx

array([[[6],
        [7],
        [8]]])

In [5]:
cx

array([[[9, 8, 7]]])

In [7]:
print(ax.shape,bx.shape,cx.shape)

(4, 1, 1) (1, 3, 1) (1, 1, 3)


In [10]:
result = ax+bx*cx
result

array([[[56, 50, 44],
        [65, 58, 51],
        [74, 66, 58]],

       [[57, 51, 45],
        [66, 59, 52],
        [75, 67, 59]],

       [[58, 52, 46],
        [67, 60, 53],
        [76, 68, 60]],

       [[59, 53, 47],
        [68, 61, 54],
        [77, 69, 61]]])

# 线性代数
简单的数组运算

In [13]:
from numpy import *
from numpy.linalg import *
a = array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [14]:
a.transpose()#转置运算

array([[1, 3],
       [2, 4]])

In [16]:
inv(a)#矩阵求逆

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
det(a)#矩阵行列式

-2.0000000000000004

In [20]:
u = eye(2)#"eye"  eaual to  "I"  单位阵
u

array([[1., 0.],
       [0., 1.]])

In [24]:
a = array([[1,2],[3,4]])
a.shape
print(a)

[[1 2]
 [3 4]]


In [22]:
dot(a,a)#矩阵乘积

array([[ 7, 10],
       [15, 22]])

In [23]:
trace(u)#u是单位阵

2.0

In [25]:
y = array([[5],[7]])
solve(a,y)#ax=y  return  x  

array([[-3.],
       [ 4.]])

# 矩阵简单总结

In [33]:
from numpy import *
A = matrix('1 2;3 4')
A

matrix([[1, 2],
        [3, 4]])

In [34]:
type(A
)

numpy.matrix

In [35]:
A.T#矩阵转置      等同于数组。transpose

matrix([[1, 3],
        [2, 4]])

In [40]:
B = matrix('3 4').T
B

matrix([[3],
        [4]])

In [41]:
A*B#矩阵乘法

matrix([[11],
        [25]])

In [42]:
dot(A,B)

matrix([[11],
        [25]])

In [43]:
solve(A,B)

matrix([[-2. ],
        [ 2.5]])

# 索引：比较矩阵和二维数组

In [50]:
A = array([0,1,2,3,4,5,6,7,8,9,10,11])
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
A.shape = (3,4)
M = mat(A.copy())
print(type(A),"\n",type(M))

<class 'numpy.ndarray'> 
 <class 'numpy.matrix'>


In [55]:
print(A,'\n****\n',M)  #看起来一样，但是性质不一样

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
****
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
print(A.shape," ",M.shape)

(3, 4)   (3, 4)


# 简单的切片

In [58]:
A[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
print(A[:,1])
print(A[:,1].shape)

[1 5 9]
(3,)


In [69]:
print(M[:,1])
print(M[:,1].shape)

[[1]
 [5]
 [9]]
(3, 1)


可以看到数组切片和矩阵切片得到的东西不一样

In [77]:
c = A[:,[1,3]]
print(c,type(c),c.shape)

[[ 1  3]
 [ 5  7]
 [ 9 11]] <class 'numpy.ndarray'> (3, 2)


# 现在做些更复杂的，比如保留第一行大于1的列，一种方法是创建布尔索引：

In [78]:
A[0,:]>1  #第一行所有列大于一的

array([False, False,  True,  True])

In [79]:
A[:,A[0,:]>1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# 拼接，组合

In [90]:
x = arange(0,10,2)

In [91]:
x

array([0, 2, 4, 6, 8])

In [92]:
y = arange(5)
y

array([0, 1, 2, 3, 4])

In [93]:
m = vstack([x,y]) #拼成二维数组 竖着拼接
m

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [94]:
xy = hstack([x,y])# 一维数组  横着拼接
xy

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])